title: bioconductor AI Agent Skills
description: Portable, platform-agnostic AI agent skills for bioconductor
remote_theme: just-the-docs/just-the-docs

# Jekyll Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "skills"
    values:
      nav_exclude: true
  -
    scope:
      path: "templates"
    values:
      nav_exclude: true
